import 'package:flutter/material.dart';

class Product {
  final int id;
  final String title, description;
  final List<String> images;
  final List<Color> colors;
  final double rating;
  final bool isFavourite, isPopular;

  Product({
    @required this.id,
    @required this.images,
    @required this.colors,
    this.rating = 0.0,
    this.isFavourite = false,
    this.isPopular = false,
    @required this.title,
    // @required this.price,
    @required this.description,
  });
}

// Our demo Products

List<Product> demoProducts = [
  Product(
    id: 1,
    images: [
      "assets/images/alarm-clock.png",
      "assets/images/horario.png",
      "assets/images/horario2.png",
      "assets/images/horario3.png",
      "assets/images/horario4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Horário das Mamadas",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 2,
    images: [
      "assets/images/wash-your-hands.png",
      "assets/images/higienizacao1.png",
      "assets/images/higienizacao2.png",
      "assets/images/higienizacao3.png",
      "assets/images/higienizacao4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Higienização",
    description: description,
    rating: 4.1,
    isPopular: true,
  ),
  Product(
    id: 3,
    images: [
      "assets/images/breastfeeding.png",
      "assets/images/posicoes1.png",
      "assets/images/posicoes2.png",
      "assets/images/posicoes3.png",
      "assets/images/posicoes4.png",
      "assets/images/posicoes5.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Posições",
    description: description,
    rating: 4.1,
    isFavourite: true,
    isPopular: true,
  ),
];
List<Product> demoProducts1 = [
  Product(
    id: 1,
    images: [
      "assets/images/heart.png",
      "assets/images/beneficios1.png",
      "assets/images/beneficios2.png",
      "assets/images/beneficios3.png",
      "assets/images/beneficios4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Benefícios do AME",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 2,
    images: [
      "assets/images/leite-materno.png",
      "assets/images/composicaoleite1.png",
      "assets/images/composicaoleite2.png",
      "assets/images/composicaoleite3.png",
      "assets/images/composicaoleite4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Composição do Leite Materno",
    description: description,
    rating: 4.1,
    isPopular: true,
  ),
  Product(
    id: 3,
    images: [
      "assets/images/breastfeeding.png",
      "assets/images/pegacorreta1.png",
      "assets/images/pegacorreta2.png",
      "assets/images/pegacorreta3.png",
      "assets/images/pegacorreta4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Pega Correta",
    description: description,
    rating: 4.1,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 4,
    images: [
      "assets/images/heart(1).png",
      "assets/images/razoes1.png",
      "assets/images/razoes2.png",
      "assets/images/razoes3.png",
      "assets/images/razoes4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Razões Para Amamentar",
    description: description,
    rating: 4.1,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 5,
    images: [
      "assets/images/hourglass.png",
      "assets/images/tempomamada.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Tempo de Mamada",
    description: description,
    rating: 4.1,
    isFavourite: true,
    isPopular: true,
  ),
];
List<Product> demoProducts2 = [
  Product(
    id: 1,
    images: [
      "assets/images/seios.png",
      "assets/images/cuidados1.png",
      "assets/images/cuidados2.png",
      "assets/images/cuidados3.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Cuidados após amamentação",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 2,
    images: [
      "assets/images/sino-de-recepcao.png",
      "assets/images/saciedade1.png",
      "assets/images/saciedade2.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Sinais de saciedade",
    description: description,
    rating: 4.1,
    isPopular: true,
  ),
];
List<Product> demoProducts3 = [
  Product(
    id: 1,
    images: [
      "assets/images/mother.png",
      "assets/images/cuidadosmae1.png",
      "assets/images/cuidadosmae2.png",
      "assets/images/cuidadosmae3.png",
      "assets/images/cuidadosmae4.png",
      "assets/images/cuidadosmae5.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Cuidados com a mãe",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
];
List<Product> demoProducts4 = [
  Product(
    id: 1,
    images: [
      "assets/images/pain.png",
      "assets/images/dor1.png",
      "assets/images/dor2.png",
      "assets/images/dor3.png",
      "assets/images/dor4.png",
      "assets/images/dor5.png",
      "assets/images/dor6.png",
      "assets/images/dor7.png",
      "assets/images/dor8.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Dor ao Amamentar",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 2,
    images: [
      "assets/images/leite-materno.png",
      "assets/images/traumas1.png",
      "assets/images/traumas2.png",
      "assets/images/traumas3.png",
      "assets/images/traumas4.png",
      "assets/images/traumas5.png",
      "assets/images/traumas6.png",
      "assets/images/traumas7.png",
      "assets/images/traumas8.png",
      "assets/images/traumas9.png",
      "assets/images/traumas10.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Traumas Mamilares",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 3,
    images: [
      "assets/images/peito.png",
      "assets/images/ingurgitamentofisio1.png",
      "assets/images/ingurgitamentofisio2.png",
      "assets/images/ingurgitamentofisio3.png",
      "assets/images/ingurgitamentofisio4.png",
      "assets/images/ingurgitamentofisio5.png",
      "assets/images/ingurgitamentofisio6.png",
      "assets/images/ingurgitamentofisio7.png",
      "assets/images/ingurgitamentofisio8.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Ingurgitamento Mamário Fisiológico",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 4,
    images: [
      "assets/images/bra.png",
      "assets/images/ingurgitamentopatologico1.png",
      "assets/images/ingurgitamentopatologico2.png",
      "assets/images/ingurgitamentopatologico3.png",
      "assets/images/ingurgitamentopatologico4.png",
      "assets/images/ingurgitamentopatologico5.png",
      "assets/images/ingurgitamentopatologico6.png",
      "assets/images/ingurgitamentopatologico7.png",
      "assets/images/ingurgitamentopatologico8.png",
      "assets/images/ingurgitamentopatologico9.png",
      "assets/images/ingurgitamentopatologico10.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Ingurgitamento Mamário Patológico",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 5,
    images: [
      "assets/images/ordenha.png",
      "assets/images/ordenha1.png",
      "assets/images/ordenha2.png",
      "assets/images/ordenha3.png",
      "assets/images/ordenha4.png",
      "assets/images/ordenha5.png",
      "assets/images/ordenha6.png",
      "assets/images/ordenha7.png",
      "assets/images/ordenha8.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Ordenha Manual das Mamas",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
];
List<Product> demoProducts5 = [
  Product(
    id: 1,
    images: [
      "assets/images/pain.png",
      "assets/images/mastite1.png",
      "assets/images/mastite2.png",
      "assets/images/mastite3.png",
      "assets/images/mastite4.png",
      "assets/images/mastite5.png",
      "assets/images/mastite6.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Mastite",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 2,
    images: [
      "assets/images/leite-materno.png",
      "assets/images/hipergalactia1.png",
      "assets/images/hipergalactia2.png",
      "assets/images/hipergalactia3.png",
      "assets/images/hipergalactia4.png",
      "assets/images/hipergalactia5.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Hipergalactia",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 3,
    images: [
      "assets/images/warning.png",
      "assets/images/hipogalactia1.png",
      "assets/images/hipogalactia2.png",
      "assets/images/hipogalactia3.png",
      "assets/images/hipogalactia4.png",
      "assets/images/hipogalactia5.png",
      "assets/images/hipogalactia6.png",
      "assets/images/hipogalactia7.png",
      "assets/images/hipogalactia8.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Hipogalactia",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
  Product(
    id: 4,
    images: [
      "assets/images/healthcare.png",
      "assets/images/apoio1.png",
      "assets/images/apoio2.png",
      "assets/images/apoio3.png",
      "assets/images/apoio4.png",
    ],
    colors: [
      Color(0xFFF6625E),
      Color(0xFF836DB8),
      Color(0xFFDECB9C),
      Colors.white,
    ],
    title: "Apoio dos serviços de saúde",
    description: description,
    rating: 4.8,
    isFavourite: true,
    isPopular: true,
  ),
];

const String description = "";
